data()
titanic <- data("Titanic")
force(Titanic)
Cal_Santiago1 <- c("CALCULO DIFERENCIAL","FUNDAMENTOS DE PROGRAMACION","MATEMATICAS DISCRETAS","INTRODUCCION A LAS TIC´S","TALLER DE ETICA","FUNDAMENTOS DE INVESTIGACION","INGLES 1")
Cal_Santiago1 <- data.frame("CALCULO DIFERENCIAL"=85,"FUNDAMENTOS DE PROGRAMACION"=90,"MATEMATICAS DISCRETAS"=83,"INTRODUCCION A LAS TIC´S"=100,"TALLER DE ETICA"=87,"FUNDAMENTOS DE INVESTIGACION"=100,"INGLES 1"=91)
Cal_Santiago1
Cal_Santiago2 <- c("CALCULO INTEGRAL","PROGRAMACION ORIENTADA A OBJETOS","MATEMATICAS DISCRETAS II","PROBABILIDAD Y ESTADISTICA","CONTABILIDAD Y COSTOS","ALGEBRA LINEAL","INGLES 2")
Cal_Santiago2 <- data.frame("CALCULO INTEGRAL"=85,"PROGRAMACION ORIENTADA A OBJETOS"=94,"MATEMATICAS DISCRETAS II"=89,"PROBABILIDAD Y ESTADISTICA"=92,"CONTABILIDAD Y COSTOS"=98,"ALGEBRA LINEAL"=100,"INGLES 2"=90)
Cal_Santiago2